# Change these first
owner: farhun1 # Your GitHub organization or username, where this repository lives
repo: upptime-pscore # The name of this repository

sites:
  - name: Whatsapp IP (57.144.143.32)
    url: http://57.144.143.32  # Added http:// to satisfy the parser
    type: globalping
    check: tcp-ping           # TCP is more reliable than ICMP for public IPs
    port: 443                 # Port 443 is standard for web services
    location: Dhaka           # Simplified location string
  - name: Cloudflare DNS Dhaka
    url: http://1.1.1.1
    type: globalping
    check: icmp-ping          # ICMP works for 1.1.1.1 because it's a DNS provider
    location: Bangladesh      # Using country name is often more stable
  - name: Wikipedia
    url: wikipedia.org
    type: globalping
    check: icmp-ping
    location: Dhaka
  - name: DNS Cloudflare
    url: 1.1.1.1
    check: icmp-ping
    location: Berlin
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
    type: globalping
  - name: Whatsapp IP (57.144.142.141)
    url: 57.144.142.141
    type: globalping
    check: "icmp-ping"
    port: 53
    location: Dhaka+BD
  - name: Cloudflare DNS
    url: 1.1.1.1
    type: globalping
    check: "icmp-ping"
    location: Dhaka+BD
  - name: Google
    check: "tcp-ping"
    url: google.com
    type: globalping
    location: Dhaka+BD
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-pscore
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Check different service IP performance"
  introMessage: Random site to check some Service IP for different Service
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
